server:
  port: 7769
spring:
  data:
    mongodb:
      uri: mongodb://messageuser:Messageuser123@47.107.219.85:3717/message
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://192.168.206.201:8888/eureka/
# 开启熔断功能
feign:
  hystrix:
    enabled: true